### ISSUE TITLE
Error 500 is returned by the API for some inputs

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-web-api#65] opened 2016-08-24 13:32 UTC
If I send the following JSON to the openfisca-france API, I get a 500 error.

``` json
{
    "scenarios": [{
        "period": 2015,
        "test_case": {
            "individus": [{
                "id": "Personne 1"
            }],
            "familles": [{
                "id": "Famille 1",
                "parents": ["Personne 1"]
            }],
            "foyers_fiscaux": [{
                "id": "Déclaration d'impôt 1",
                "declarants": ["Personne 1"]
            }],
            "menages": [{
                "id": "Logement principal 1",
                "personne_de_reference": "Personne 1"
            }]
        }
    }],
    "variables": ["rsa", "ppa", "aspa", "apl", "als", "alf", "cmu_c"]
}
```

Error in the server logs: 

```
  File "/Users/fpagnoux/.virtualenvs/mes-aides/lib/python2.7/site-packages/openfisca_web_api/controllers/calculate.py", line 84, in calculate_simulations
    simulation.calculate_output(variable_name)
  File "/Users/fpagnoux/dev/mes-aides/openfisca/openfisca/core/openfisca_core/simulations.py", line 98, in calculate_output
    return holder.calculate_output(period)
  File "/Users/fpagnoux/dev/mes-aides/openfisca/openfisca/core/openfisca_core/holders.py", line 92, in calculate_output
    return self.formula.calculate_output(period)
  File "/Users/fpagnoux/dev/mes-aides/openfisca/openfisca/core/openfisca_core/formulas.py", line 54, in calculate_output
    return self.holder.compute(period).array
  File "/Users/fpagnoux/dev/mes-aides/openfisca/openfisca/core/openfisca_core/holders.py", line 142, in compute
    formula_dated_holder.period, column.name)
AssertionError: Requested period 2015 differs from 2015-01 returned by variable cmu_c
```

This seems to happen only when asking to calculate `cmu_c`, and not with `rsa`, etc. I don't understand why, neither why the error is not catched by something. Maybe something about `calculate_output` ?

**Comment by cbenz** [comment] 2016-08-24 13:55
The thing is `cmu_c` seems to be monthly. So you need to request `2015-MM` in your test case.

What to do if your `variables` list mixed monthly and yearly variables?

We could use `calculate_output` systematically so that the result would return a dict like:

```json
{
  "values": {
    "cmu_c": {"2015-01": [9999]}
  }
}
```

What do you think about it?

**Comment by cbenz** [comment] 2016-08-24 13:59
Normally the API should return, even with an exception like that, a JSON saying "internal server error". Can you copy-paste it?

**Comment by MattiSG** [comment] 2017-03-02 09:58
Duplicate of #60.

**Closed by MattiSG** 2017-03-02 09:58 UTC
Labels: current-sprint
