### ISSUE TITLE
Document the actual production deploy method

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-web-api#83] opened 2017-02-07 15:43 UTC
This [section of `README.md`](https://github.com/openfisca/openfisca-web-api/blob/master/README.md#deploy-in-production) is wrong.

Today we deploy with nginx which reverse-proxifies to [gunicorn](http://gunicorn.org/).

- [x] commit a production directory with template files
- [x] move the README.md section to `production/README.md`

**Comment by MattiSG** [comment] 2017-02-28 19:13
Duplicate of #82.

**Closed by MattiSG** 2017-02-28 19:13 UTC
Labels: in progress
