### ISSUE TITLE
Send a clear error message when the user asks a variable for an incompatible period

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-web-api#74] opened 2017-01-04 17:30 UTC
As a user of the API,
When I ask to compute a variable (e.g. PPA) for a period it can't be calculated (e.g. a year),
I get a clear error message to help me understand why my request is rejected

(Instead of a server error like today)

**Comment by MattiSG** [comment] 2017-03-02 09:57
Duplicate of #60.

**Closed by MattiSG** 2017-03-02 09:57 UTC
