### ISSUE TITLE
Exception mentioning period mismatch

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-web-api#88] opened 2017-02-09 10:14 UTC
Here is a stack trace we receive sometimes:
```
URL: http://api.openfisca.fr/api/1/calculate
Module weberror.errormiddleware:171 in __call__
>>  app_iter = self.application(environ, sr_checker)
Module webob.dec:131 in __call__
>>  resp = self.call_func(req, *args, **self.kwargs)
Module webob.dec:196 in call_func
>>  return self.func(req, *args, **kwargs)
Module openfisca_web_api.application:37 in set_application_url
>>  return req.get_response(app)
Module webob.request:1316 in send
>>  application, catch_exc_info=False)
Module webob.request:1280 in call_application
>>  app_iter = application(self.environ, start_response)
Module openfisca_web_api.urls:115 in router
>>  return app(req.environ, start_response)
Module webob.dec:131 in __call__
>>  resp = self.call_func(req, *args, **self.kwargs)
Module webob.dec:196 in call_func
>>  return self.func(req, *args, **kwargs)
Module openfisca_web_api.controllers.calculate:351 in api1_calculate
>>  base_simulations = calculate_simulations(scenarios, data['variables'], trace = trace_simulations)
Module openfisca_web_api.controllers.calculate:84 in calculate_simulations
>>  simulation.calculate_output(variable_name)
Module openfisca_core.simulations:93 in calculate_output
>>  return holder.calculate_output(period)
Module openfisca_core.holders:91 in calculate_output
>>  return self.formula.calculate_output(period)
Module openfisca_core.formulas:56 in calculate_output
>>  return self.holder.compute(period).array
Module openfisca_core.holders:139 in compute
>>  formula_dated_holder.period, column.name)
AssertionError: Requested period 2017 differs from 2017-01 returned by variable cmu_c
```

**Comment by MattiSG** [comment] 2017-02-28 19:15
The user only receives a blank page with the text `A server error occurred. Please contact the administrator`.

**Comment by MattiSG** [comment] 2017-02-28 19:21
Duplicate of #65.

**Closed by MattiSG** 2017-02-28 19:21 UTC
Labels: current-sprint
